name: "Pull Request Labeler"
on:
 pull_request:
  types: [synchronize, opened, reopened, edited, closed]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        labels: "hacktoberfest2022"
