name: issue-automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened,reopend]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "hacktoberfest22, hacktoberfest2022"
          ignore-if-labeled: true
        
